evaluation_labeled_data_path: []
logs_root_path: /home/zhouxian/git/pixel-feature-learning/pdc/logs_proto/cooking_march
object_id: cheese_01
test:
- cheese_01_1
- cheese_01_2
- cheese_01_3
train:
- cheese_01_1
- cheese_01_2
- cheese_01_3
