evaluation_labeled_data_path: []
logs_root_path: /home/zhouxian/git/pixel-feature-learning/pdc/logs_proto/cooking_march
object_id: Cucumber_Slice_convert
test:
- Cucumber_Slice_convert_1
- Cucumber_Slice_convert_2
- Cucumber_Slice_convert_3
train:
- Cucumber_Slice_convert_1
- Cucumber_Slice_convert_2
- Cucumber_Slice_convert_3
