logs_root_path: /home/zhouxian/git/pytorch-dense-correspondence/pdc/logs_proto
object_id: "duck"
train:
- "duck1"
- "duck2"
- "duck3"
test:
- "duck1"
- "duck2"
- "duck3"
evaluation_labeled_data_path: 
- "code/data_volume/pdc/evaluation_labeled_data/caterpillar_cross_scene_labels.yaml"
