logs_root_path: code/data_volume/pdc/logs_proto
object_id: "star_bot"
train:
- "2018-05-04-19-42-34"
test:
- "2018-05-04-20-08-47"
- "2018-05-04-20-10-32"
evaluation_labeled_data_path: 
- "nowhereyet"