logs_root_path: /home/zhouxian/git/pytorch-dense-correspondence/pdc/logs_proto

single_object_scenes_config_files:
- jalapeno_pepper_train.yaml
- chilli_pepper_on_white_plate_custom_1_train.yaml
- chilli_pepper_on_white_plate_custom_2_train.yaml

multi_object_scenes_config_files: []